package com.CarServieStation.backend.entity;

public enum ColorType {
    RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET, PINK, BLACK, WHITE,
    GRAY, BROWN, CYAN, MAGENTA, TAN, CREAM, GOLD, SILVER, BRONZE, MAROON,
    NAVY, OLIVE, TEAL, AQUA, LIME, CORAL, PEACH, AMBER, JADE, SAPPHIRE,
    PERIWINKLE, BEIGE, LAVENDER, MINT, CHARCOAL, CHAMPAGNE, TURQUOISE,
    RASPBERRY, PLUM, ORCHID, BURGUNDY, FUCHSIA
}

